# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.reply_v1alpha1_api import ReplyV1alpha1Api


class TestReplyV1alpha1Api(unittest.TestCase):
    """ReplyV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ReplyV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_reply(self) -> None:
        """Test case for create_reply

        """
        pass

    def test_delete_reply(self) -> None:
        """Test case for delete_reply

        """
        pass

    def test_get_reply(self) -> None:
        """Test case for get_reply

        """
        pass

    def test_list_reply(self) -> None:
        """Test case for list_reply

        """
        pass

    def test_patch_reply(self) -> None:
        """Test case for patch_reply

        """
        pass

    def test_update_reply(self) -> None:
        """Test case for update_reply

        """
        pass


if __name__ == '__main__':
    unittest.main()
