# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.comment_owner import CommentOwner

class TestCommentOwner(unittest.TestCase):
    """CommentOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommentOwner:
        """Test CommentOwner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommentOwner`
        """
        model = CommentOwner()
        if include_optional:
            return CommentOwner(
                annotations = {
                    'key' : ''
                    },
                display_name = '',
                kind = '0',
                name = ''
            )
        else:
            return CommentOwner(
                kind = '0',
                name = '',
        )
        """

    def testCommentOwner(self):
        """Test CommentOwner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
