# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.user_spec import UserSpec

class TestUserSpec(unittest.TestCase):
    """UserSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSpec:
        """Test UserSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSpec`
        """
        model = UserSpec()
        if include_optional:
            return UserSpec(
                avatar = '',
                bio = '',
                disabled = True,
                display_name = '',
                email = '',
                email_verified = True,
                login_history_limit = 56,
                password = '',
                phone = '',
                registered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                totp_encrypted_secret = '',
                two_factor_auth_enabled = True
            )
        else:
            return UserSpec(
                display_name = '',
                email = '',
        )
        """

    def testUserSpec(self):
        """Test UserSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
