# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.auth_provider_list import AuthProviderList

class TestAuthProviderList(unittest.TestCase):
    """AuthProviderList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthProviderList:
        """Test AuthProviderList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthProviderList`
        """
        model = AuthProviderList()
        if include_optional:
            return AuthProviderList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.auth_provider.AuthProvider(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        spec = halo_client.models.auth_provider_spec.AuthProviderSpec(
                            auth_type = 'FORM', 
                            authentication_url = '', 
                            binding_url = '', 
                            config_map_ref = halo_client.models.config_map_ref.ConfigMapRef(
                                name = '0', ), 
                            description = '', 
                            display_name = '', 
                            help_page = '', 
                            logo = '', 
                            method = '', 
                            remember_me_support = True, 
                            setting_ref = halo_client.models.setting_ref.SettingRef(
                                group = '0', 
                                name = '0', ), 
                            unbind_url = '', 
                            website = '', ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56
            )
        else:
            return AuthProviderList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.auth_provider.AuthProvider(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        spec = halo_client.models.auth_provider_spec.AuthProviderSpec(
                            auth_type = 'FORM', 
                            authentication_url = '', 
                            binding_url = '', 
                            config_map_ref = halo_client.models.config_map_ref.ConfigMapRef(
                                name = '0', ), 
                            description = '', 
                            display_name = '', 
                            help_page = '', 
                            logo = '', 
                            method = '', 
                            remember_me_support = True, 
                            setting_ref = halo_client.models.setting_ref.SettingRef(
                                group = '0', 
                                name = '0', ), 
                            unbind_url = '', 
                            website = '', ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56,
        )
        """

    def testAuthProviderList(self):
        """Test AuthProviderList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
