# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.navigation_post_vo import NavigationPostVo

class TestNavigationPostVo(unittest.TestCase):
    """NavigationPostVo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NavigationPostVo:
        """Test NavigationPostVo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NavigationPostVo`
        """
        model = NavigationPostVo()
        if include_optional:
            return NavigationPostVo(
                current = halo_client.models.post_vo.PostVo(
                    categories = [
                        halo_client.models.category_vo.CategoryVo(
                            metadata = halo_client.models.metadata.Metadata(
                                annotations = {
                                    'key' : ''
                                    }, 
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                finalizers = [
                                    ''
                                    ], 
                                generate_name = '', 
                                labels = {
                                    'key' : ''
                                    }, 
                                name = '', 
                                version = 56, ), 
                            post_count = 56, 
                            spec = halo_client.models.category_spec.CategorySpec(
                                children = [
                                    ''
                                    ], 
                                cover = '', 
                                description = '', 
                                display_name = '0', 
                                hide_from_list = True, 
                                post_template = '', 
                                prevent_parent_post_cascade_query = True, 
                                priority = 56, 
                                slug = '0', 
                                template = '', ), 
                            status = halo_client.models.category_status.CategoryStatus(
                                permalink = '', 
                                post_count = 56, 
                                visible_post_count = 56, ), )
                        ], 
                    content = halo_client.models.content_vo.ContentVo(
                        raw = '', ), 
                    contributors = [
                        halo_client.models.contributor_vo.ContributorVo(
                            avatar = '', 
                            bio = '', 
                            display_name = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generate_name = '', 
                                name = '', 
                                version = 56, ), 
                            name = '', 
                            permalink = '', )
                        ], 
                    metadata = , 
                    owner = halo_client.models.contributor_vo.ContributorVo(
                        avatar = '', 
                        bio = '', 
                        display_name = '', 
                        metadata = , 
                        name = '', 
                        permalink = '', ), 
                    spec = halo_client.models.post_spec.PostSpec(
                        allow_comment = True, 
                        base_snapshot = '', 
                        cover = '', 
                        deleted = True, 
                        excerpt = halo_client.models.excerpt.Excerpt(
                            auto_generate = True, 
                            raw = '', ), 
                        head_snapshot = '', 
                        html_metas = [
                            {
                                'key' : ''
                                }
                            ], 
                        pinned = True, 
                        priority = 56, 
                        publish = True, 
                        publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        release_snapshot = '', 
                        slug = '0', 
                        tags = [
                            ''
                            ], 
                        template = '', 
                        title = '0', 
                        visible = 'PUBLIC', ), 
                    stats = halo_client.models.stats_vo.StatsVo(
                        comment = 56, 
                        upvote = 56, 
                        visit = 56, ), 
                    status = halo_client.models.post_status.PostStatus(
                        comments_count = 56, 
                        conditions = [
                            halo_client.models.condition.Condition(
                                last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '', 
                                reason = 'AbUUGjjNSwg1_bs:ZayIMrKdgNvb7gvxmPb:GcsM72ate2RA9:q4w2l5eH5XxEz06awo', 
                                status = 'TRUE', 
                                type = '8.z.c.e.0.3zmetozkhdomha1bae37b8ocvx8o53ow2eg7p6qw9qklp6l4y010fog5ugcajvnh6nzn2yp6d7tmo7zxedi-pkbmh3.o.34ncp9spy.k.hf9r1ly-n2jyba-zuswj171d3kx6.vyykb66fgvcwlpe6fjm6div96l1hmssf5by0949ps5we28.kiw57.m.n50o3hq25-ctix-xt8fyuzw85-6ymflfzgfzdm4gro1y8vcn4nxdzyo.t2bsdqi-90qr77qnqf26kpzuf5a652r9yc8wgfitooko8u.wj5.b6ca0gq8ejs584qp107f5qv9ze3gk7q64-5mecujmelufynb1wtb8v2n1x9-y9o36-1meqixpaj.x.zay1yebs1kiembt-ho5.8.864bew-vpjuuty7-xv4qjygg3hwqd-5gynywalvhvvesyveyxp35spjahpsiagrj0jehh3a3x8z9axqtswj383252z.d6d4ifob3rgi7j1fao-vb9l55lz.bsk1mqype9zx3n6q-u55t879v1lf.1.k.isf-swgdlh.0.m4u5aoqakjc4xlcmbpoy4ndizk4s3cdhxttexawd8mnl6e4uzxalowdqy9rokd32ct-w5p-yt-emwrzfi.lulqkw0osnqktff9fp6xbt97440w4wt3xjayovyb7flljlnosgtrofp.o.j.p5-2p577rg1fwny6cq1e2d3p5aa62rscqk6cxzeqcrvjnbqd52lumjr3qda19c-7skjef4ovphp57sme4j.v/uvfKd3LB7Nke4pyLFXi20uV', )
                            ], 
                        hide_from_list = True, 
                        in_progress = True, 
                        last_modify_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        observed_version = 56, 
                        permalink = '', 
                        phase = '', ), 
                    tags = [
                        halo_client.models.tag_vo.TagVo(
                            metadata = , 
                            post_count = 56, )
                        ], ),
                next = halo_client.models.post_vo.PostVo(
                    categories = [
                        halo_client.models.category_vo.CategoryVo(
                            metadata = halo_client.models.metadata.Metadata(
                                annotations = {
                                    'key' : ''
                                    }, 
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                finalizers = [
                                    ''
                                    ], 
                                generate_name = '', 
                                labels = {
                                    'key' : ''
                                    }, 
                                name = '', 
                                version = 56, ), 
                            post_count = 56, 
                            spec = halo_client.models.category_spec.CategorySpec(
                                children = [
                                    ''
                                    ], 
                                cover = '', 
                                description = '', 
                                display_name = '0', 
                                hide_from_list = True, 
                                post_template = '', 
                                prevent_parent_post_cascade_query = True, 
                                priority = 56, 
                                slug = '0', 
                                template = '', ), 
                            status = halo_client.models.category_status.CategoryStatus(
                                permalink = '', 
                                post_count = 56, 
                                visible_post_count = 56, ), )
                        ], 
                    content = halo_client.models.content_vo.ContentVo(
                        raw = '', ), 
                    contributors = [
                        halo_client.models.contributor_vo.ContributorVo(
                            avatar = '', 
                            bio = '', 
                            display_name = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generate_name = '', 
                                name = '', 
                                version = 56, ), 
                            name = '', 
                            permalink = '', )
                        ], 
                    metadata = , 
                    owner = halo_client.models.contributor_vo.ContributorVo(
                        avatar = '', 
                        bio = '', 
                        display_name = '', 
                        metadata = , 
                        name = '', 
                        permalink = '', ), 
                    spec = halo_client.models.post_spec.PostSpec(
                        allow_comment = True, 
                        base_snapshot = '', 
                        cover = '', 
                        deleted = True, 
                        excerpt = halo_client.models.excerpt.Excerpt(
                            auto_generate = True, 
                            raw = '', ), 
                        head_snapshot = '', 
                        html_metas = [
                            {
                                'key' : ''
                                }
                            ], 
                        pinned = True, 
                        priority = 56, 
                        publish = True, 
                        publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        release_snapshot = '', 
                        slug = '0', 
                        tags = [
                            ''
                            ], 
                        template = '', 
                        title = '0', 
                        visible = 'PUBLIC', ), 
                    stats = halo_client.models.stats_vo.StatsVo(
                        comment = 56, 
                        upvote = 56, 
                        visit = 56, ), 
                    status = halo_client.models.post_status.PostStatus(
                        comments_count = 56, 
                        conditions = [
                            halo_client.models.condition.Condition(
                                last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '', 
                                reason = 'AbUUGjjNSwg1_bs:ZayIMrKdgNvb7gvxmPb:GcsM72ate2RA9:q4w2l5eH5XxEz06awo', 
                                status = 'TRUE', 
                                type = '8.z.c.e.0.3zmetozkhdomha1bae37b8ocvx8o53ow2eg7p6qw9qklp6l4y010fog5ugcajvnh6nzn2yp6d7tmo7zxedi-pkbmh3.o.34ncp9spy.k.hf9r1ly-n2jyba-zuswj171d3kx6.vyykb66fgvcwlpe6fjm6div96l1hmssf5by0949ps5we28.kiw57.m.n50o3hq25-ctix-xt8fyuzw85-6ymflfzgfzdm4gro1y8vcn4nxdzyo.t2bsdqi-90qr77qnqf26kpzuf5a652r9yc8wgfitooko8u.wj5.b6ca0gq8ejs584qp107f5qv9ze3gk7q64-5mecujmelufynb1wtb8v2n1x9-y9o36-1meqixpaj.x.zay1yebs1kiembt-ho5.8.864bew-vpjuuty7-xv4qjygg3hwqd-5gynywalvhvvesyveyxp35spjahpsiagrj0jehh3a3x8z9axqtswj383252z.d6d4ifob3rgi7j1fao-vb9l55lz.bsk1mqype9zx3n6q-u55t879v1lf.1.k.isf-swgdlh.0.m4u5aoqakjc4xlcmbpoy4ndizk4s3cdhxttexawd8mnl6e4uzxalowdqy9rokd32ct-w5p-yt-emwrzfi.lulqkw0osnqktff9fp6xbt97440w4wt3xjayovyb7flljlnosgtrofp.o.j.p5-2p577rg1fwny6cq1e2d3p5aa62rscqk6cxzeqcrvjnbqd52lumjr3qda19c-7skjef4ovphp57sme4j.v/uvfKd3LB7Nke4pyLFXi20uV', )
                            ], 
                        hide_from_list = True, 
                        in_progress = True, 
                        last_modify_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        observed_version = 56, 
                        permalink = '', 
                        phase = '', ), 
                    tags = [
                        halo_client.models.tag_vo.TagVo(
                            metadata = , 
                            post_count = 56, )
                        ], ),
                previous = halo_client.models.post_vo.PostVo(
                    categories = [
                        halo_client.models.category_vo.CategoryVo(
                            metadata = halo_client.models.metadata.Metadata(
                                annotations = {
                                    'key' : ''
                                    }, 
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                finalizers = [
                                    ''
                                    ], 
                                generate_name = '', 
                                labels = {
                                    'key' : ''
                                    }, 
                                name = '', 
                                version = 56, ), 
                            post_count = 56, 
                            spec = halo_client.models.category_spec.CategorySpec(
                                children = [
                                    ''
                                    ], 
                                cover = '', 
                                description = '', 
                                display_name = '0', 
                                hide_from_list = True, 
                                post_template = '', 
                                prevent_parent_post_cascade_query = True, 
                                priority = 56, 
                                slug = '0', 
                                template = '', ), 
                            status = halo_client.models.category_status.CategoryStatus(
                                permalink = '', 
                                post_count = 56, 
                                visible_post_count = 56, ), )
                        ], 
                    content = halo_client.models.content_vo.ContentVo(
                        raw = '', ), 
                    contributors = [
                        halo_client.models.contributor_vo.ContributorVo(
                            avatar = '', 
                            bio = '', 
                            display_name = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generate_name = '', 
                                name = '', 
                                version = 56, ), 
                            name = '', 
                            permalink = '', )
                        ], 
                    metadata = , 
                    owner = halo_client.models.contributor_vo.ContributorVo(
                        avatar = '', 
                        bio = '', 
                        display_name = '', 
                        metadata = , 
                        name = '', 
                        permalink = '', ), 
                    spec = halo_client.models.post_spec.PostSpec(
                        allow_comment = True, 
                        base_snapshot = '', 
                        cover = '', 
                        deleted = True, 
                        excerpt = halo_client.models.excerpt.Excerpt(
                            auto_generate = True, 
                            raw = '', ), 
                        head_snapshot = '', 
                        html_metas = [
                            {
                                'key' : ''
                                }
                            ], 
                        pinned = True, 
                        priority = 56, 
                        publish = True, 
                        publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        release_snapshot = '', 
                        slug = '0', 
                        tags = [
                            ''
                            ], 
                        template = '', 
                        title = '0', 
                        visible = 'PUBLIC', ), 
                    stats = halo_client.models.stats_vo.StatsVo(
                        comment = 56, 
                        upvote = 56, 
                        visit = 56, ), 
                    status = halo_client.models.post_status.PostStatus(
                        comments_count = 56, 
                        conditions = [
                            halo_client.models.condition.Condition(
                                last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '', 
                                reason = 'AbUUGjjNSwg1_bs:ZayIMrKdgNvb7gvxmPb:GcsM72ate2RA9:q4w2l5eH5XxEz06awo', 
                                status = 'TRUE', 
                                type = '8.z.c.e.0.3zmetozkhdomha1bae37b8ocvx8o53ow2eg7p6qw9qklp6l4y010fog5ugcajvnh6nzn2yp6d7tmo7zxedi-pkbmh3.o.34ncp9spy.k.hf9r1ly-n2jyba-zuswj171d3kx6.vyykb66fgvcwlpe6fjm6div96l1hmssf5by0949ps5we28.kiw57.m.n50o3hq25-ctix-xt8fyuzw85-6ymflfzgfzdm4gro1y8vcn4nxdzyo.t2bsdqi-90qr77qnqf26kpzuf5a652r9yc8wgfitooko8u.wj5.b6ca0gq8ejs584qp107f5qv9ze3gk7q64-5mecujmelufynb1wtb8v2n1x9-y9o36-1meqixpaj.x.zay1yebs1kiembt-ho5.8.864bew-vpjuuty7-xv4qjygg3hwqd-5gynywalvhvvesyveyxp35spjahpsiagrj0jehh3a3x8z9axqtswj383252z.d6d4ifob3rgi7j1fao-vb9l55lz.bsk1mqype9zx3n6q-u55t879v1lf.1.k.isf-swgdlh.0.m4u5aoqakjc4xlcmbpoy4ndizk4s3cdhxttexawd8mnl6e4uzxalowdqy9rokd32ct-w5p-yt-emwrzfi.lulqkw0osnqktff9fp6xbt97440w4wt3xjayovyb7flljlnosgtrofp.o.j.p5-2p577rg1fwny6cq1e2d3p5aa62rscqk6cxzeqcrvjnbqd52lumjr3qda19c-7skjef4ovphp57sme4j.v/uvfKd3LB7Nke4pyLFXi20uV', )
                            ], 
                        hide_from_list = True, 
                        in_progress = True, 
                        last_modify_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        observed_version = 56, 
                        permalink = '', 
                        phase = '', ), 
                    tags = [
                        halo_client.models.tag_vo.TagVo(
                            metadata = , 
                            post_count = 56, )
                        ], )
            )
        else:
            return NavigationPostVo(
        )
        """

    def testNavigationPostVo(self):
        """Test NavigationPostVo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
