# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.policy_template import PolicyTemplate

class TestPolicyTemplate(unittest.TestCase):
    """PolicyTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyTemplate:
        """Test PolicyTemplate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyTemplate`
        """
        model = PolicyTemplate()
        if include_optional:
            return PolicyTemplate(
                api_version = '',
                kind = '',
                metadata = halo_client.models.metadata.Metadata(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    name = '', 
                    version = 56, ),
                spec = halo_client.models.policy_template_spec.PolicyTemplateSpec(
                    display_name = '', 
                    setting_name = '', )
            )
        else:
            return PolicyTemplate(
                api_version = '',
                kind = '',
                metadata = halo_client.models.metadata.Metadata(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    name = '', 
                    version = 56, ),
        )
        """

    def testPolicyTemplate(self):
        """Test PolicyTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
