# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.post_spec import PostSpec

class TestPostSpec(unittest.TestCase):
    """PostSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSpec:
        """Test PostSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSpec`
        """
        model = PostSpec()
        if include_optional:
            return PostSpec(
                allow_comment = True,
                base_snapshot = '',
                categories = [
                    ''
                    ],
                cover = '',
                deleted = True,
                excerpt = halo_client.models.excerpt.Excerpt(
                    auto_generate = True, 
                    raw = '', ),
                head_snapshot = '',
                html_metas = [
                    {
                        'key' : ''
                        }
                    ],
                owner = '',
                pinned = True,
                priority = 56,
                publish = True,
                publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                release_snapshot = '',
                slug = '0',
                tags = [
                    ''
                    ],
                template = '',
                title = '0',
                visible = 'PUBLIC'
            )
        else:
            return PostSpec(
                allow_comment = True,
                deleted = True,
                excerpt = halo_client.models.excerpt.Excerpt(
                    auto_generate = True, 
                    raw = '', ),
                pinned = True,
                priority = 56,
                publish = True,
                slug = '0',
                title = '0',
                visible = 'PUBLIC',
        )
        """

    def testPostSpec(self):
        """Test PostSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
