# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.user_v1alpha1_console_api import UserV1alpha1ConsoleApi


class TestUserV1alpha1ConsoleApi(unittest.TestCase):
    """UserV1alpha1ConsoleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserV1alpha1ConsoleApi()

    def tearDown(self) -> None:
        pass

    def test_change_anyone_password(self) -> None:
        """Test case for change_anyone_password

        """
        pass

    def test_change_own_password(self) -> None:
        """Test case for change_own_password

        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        """
        pass

    def test_delete_user_avatar(self) -> None:
        """Test case for delete_user_avatar

        """
        pass

    def test_disable_user(self) -> None:
        """Test case for disable_user

        """
        pass

    def test_enable_user(self) -> None:
        """Test case for enable_user

        """
        pass

    def test_get_current_user_detail(self) -> None:
        """Test case for get_current_user_detail

        """
        pass

    def test_get_permissions(self) -> None:
        """Test case for get_permissions

        """
        pass

    def test_get_user_detail(self) -> None:
        """Test case for get_user_detail

        """
        pass

    def test_grant_permission(self) -> None:
        """Test case for grant_permission

        """
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        """
        pass

    def test_send_email_verification_code(self) -> None:
        """Test case for send_email_verification_code

        """
        pass

    def test_update_current_user(self) -> None:
        """Test case for update_current_user

        """
        pass

    def test_upload_user_avatar(self) -> None:
        """Test case for upload_user_avatar

        """
        pass

    def test_verify_email(self) -> None:
        """Test case for verify_email

        """
        pass


if __name__ == '__main__':
    unittest.main()
