# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.listed_post_list import ListedPostList

class TestListedPostList(unittest.TestCase):
    """ListedPostList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListedPostList:
        """Test ListedPostList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListedPostList`
        """
        model = ListedPostList()
        if include_optional:
            return ListedPostList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.listed_post.ListedPost(
                        categories = [
                            halo_client.models.category.Category(
                                api_version = '', 
                                kind = '', 
                                metadata = halo_client.models.metadata.Metadata(
                                    annotations = {
                                        'key' : ''
                                        }, 
                                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    finalizers = [
                                        ''
                                        ], 
                                    generate_name = '', 
                                    labels = {
                                        'key' : ''
                                        }, 
                                    name = '', 
                                    version = 56, ), 
                                spec = halo_client.models.category_spec.CategorySpec(
                                    children = [
                                        ''
                                        ], 
                                    cover = '', 
                                    description = '', 
                                    display_name = '0', 
                                    hide_from_list = True, 
                                    post_template = '', 
                                    prevent_parent_post_cascade_query = True, 
                                    priority = 56, 
                                    slug = '0', 
                                    template = '', ), 
                                status = halo_client.models.category_status.CategoryStatus(
                                    permalink = '', 
                                    post_count = 56, 
                                    visible_post_count = 56, ), )
                            ], 
                        contributors = [
                            halo_client.models.contributor.Contributor(
                                avatar = '', 
                                display_name = '', 
                                name = '', )
                            ], 
                        owner = halo_client.models.contributor.Contributor(
                            avatar = '', 
                            display_name = '', 
                            name = '', ), 
                        post = halo_client.models.post.Post(
                            api_version = '', 
                            kind = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generate_name = '', 
                                name = '', 
                                version = 56, ), 
                            spec = halo_client.models.post_spec.PostSpec(
                                allow_comment = True, 
                                base_snapshot = '', 
                                cover = '', 
                                deleted = True, 
                                excerpt = halo_client.models.excerpt.Excerpt(
                                    auto_generate = True, 
                                    raw = '', ), 
                                head_snapshot = '', 
                                html_metas = [
                                    {
                                        'key' : ''
                                        }
                                    ], 
                                pinned = True, 
                                priority = 56, 
                                publish = True, 
                                publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                release_snapshot = '', 
                                slug = '0', 
                                tags = [
                                    ''
                                    ], 
                                template = '', 
                                title = '0', 
                                visible = 'PUBLIC', ), ), 
                        stats = halo_client.models.stats.Stats(
                            approved_comment = 56, 
                            total_comment = 56, 
                            upvote = 56, 
                            visit = 56, ), 
                        tags = [
                            halo_client.models.tag.Tag(
                                api_version = '', 
                                kind = '', 
                                metadata = , 
                                spec = halo_client.models.tag_spec.TagSpec(
                                    color = '#2EC', 
                                    cover = '', 
                                    display_name = '0', 
                                    slug = '0', ), )
                            ], )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56
            )
        else:
            return ListedPostList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.listed_post.ListedPost(
                        categories = [
                            halo_client.models.category.Category(
                                api_version = '', 
                                kind = '', 
                                metadata = halo_client.models.metadata.Metadata(
                                    annotations = {
                                        'key' : ''
                                        }, 
                                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    finalizers = [
                                        ''
                                        ], 
                                    generate_name = '', 
                                    labels = {
                                        'key' : ''
                                        }, 
                                    name = '', 
                                    version = 56, ), 
                                spec = halo_client.models.category_spec.CategorySpec(
                                    children = [
                                        ''
                                        ], 
                                    cover = '', 
                                    description = '', 
                                    display_name = '0', 
                                    hide_from_list = True, 
                                    post_template = '', 
                                    prevent_parent_post_cascade_query = True, 
                                    priority = 56, 
                                    slug = '0', 
                                    template = '', ), 
                                status = halo_client.models.category_status.CategoryStatus(
                                    permalink = '', 
                                    post_count = 56, 
                                    visible_post_count = 56, ), )
                            ], 
                        contributors = [
                            halo_client.models.contributor.Contributor(
                                avatar = '', 
                                display_name = '', 
                                name = '', )
                            ], 
                        owner = halo_client.models.contributor.Contributor(
                            avatar = '', 
                            display_name = '', 
                            name = '', ), 
                        post = halo_client.models.post.Post(
                            api_version = '', 
                            kind = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generate_name = '', 
                                name = '', 
                                version = 56, ), 
                            spec = halo_client.models.post_spec.PostSpec(
                                allow_comment = True, 
                                base_snapshot = '', 
                                cover = '', 
                                deleted = True, 
                                excerpt = halo_client.models.excerpt.Excerpt(
                                    auto_generate = True, 
                                    raw = '', ), 
                                head_snapshot = '', 
                                html_metas = [
                                    {
                                        'key' : ''
                                        }
                                    ], 
                                pinned = True, 
                                priority = 56, 
                                publish = True, 
                                publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                release_snapshot = '', 
                                slug = '0', 
                                tags = [
                                    ''
                                    ], 
                                template = '', 
                                title = '0', 
                                visible = 'PUBLIC', ), ), 
                        stats = halo_client.models.stats.Stats(
                            approved_comment = 56, 
                            total_comment = 56, 
                            upvote = 56, 
                            visit = 56, ), 
                        tags = [
                            halo_client.models.tag.Tag(
                                api_version = '', 
                                kind = '', 
                                metadata = , 
                                spec = halo_client.models.tag_spec.TagSpec(
                                    color = '#2EC', 
                                    cover = '', 
                                    display_name = '0', 
                                    slug = '0', ), )
                            ], )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56,
        )
        """

    def testListedPostList(self):
        """Test ListedPostList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
