# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.user_connection_spec import UserConnectionSpec

class TestUserConnectionSpec(unittest.TestCase):
    """UserConnectionSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConnectionSpec:
        """Test UserConnectionSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConnectionSpec`
        """
        model = UserConnectionSpec()
        if include_optional:
            return UserConnectionSpec(
                provider_user_id = '',
                registration_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                username = ''
            )
        else:
            return UserConnectionSpec(
                provider_user_id = '',
                registration_id = '',
                username = '',
        )
        """

    def testUserConnectionSpec(self):
        """Test UserConnectionSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
