# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.site_stats_vo import SiteStatsVo

class TestSiteStatsVo(unittest.TestCase):
    """SiteStatsVo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteStatsVo:
        """Test SiteStatsVo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteStatsVo`
        """
        model = SiteStatsVo()
        if include_optional:
            return SiteStatsVo(
                category = 56,
                comment = 56,
                post = 56,
                upvote = 56,
                visit = 56
            )
        else:
            return SiteStatsVo(
        )
        """

    def testSiteStatsVo(self):
        """Test SiteStatsVo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
