# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.notifier_v1alpha1_console_api import NotifierV1alpha1ConsoleApi


class TestNotifierV1alpha1ConsoleApi(unittest.TestCase):
    """NotifierV1alpha1ConsoleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotifierV1alpha1ConsoleApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_sender_config(self) -> None:
        """Test case for fetch_sender_config

        """
        pass

    def test_save_sender_config(self) -> None:
        """Test case for save_sender_config

        """
        pass

    def test_verify_email_sender_config(self) -> None:
        """Test case for verify_email_sender_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
