# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.reply_vo_list import ReplyVoList

class TestReplyVoList(unittest.TestCase):
    """ReplyVoList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReplyVoList:
        """Test ReplyVoList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReplyVoList`
        """
        model = ReplyVoList()
        if include_optional:
            return ReplyVoList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.reply_vo.ReplyVo(
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        owner = halo_client.models.owner_info.OwnerInfo(
                            avatar = '', 
                            display_name = '', 
                            email = '', 
                            kind = '', 
                            name = '', ), 
                        spec = halo_client.models.reply_spec.ReplySpec(
                            allow_notification = True, 
                            approved = True, 
                            approved_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            comment_name = '0', 
                            content = '0', 
                            creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            hidden = True, 
                            ip_address = '', 
                            owner = halo_client.models.comment_owner.CommentOwner(
                                display_name = '', 
                                kind = '0', 
                                name = '', ), 
                            priority = 56, 
                            quote_reply = '', 
                            raw = '0', 
                            top = True, 
                            user_agent = '', ), 
                        stats = halo_client.models.comment_stats_vo.CommentStatsVo(
                            upvote = 56, ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56
            )
        else:
            return ReplyVoList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.reply_vo.ReplyVo(
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        owner = halo_client.models.owner_info.OwnerInfo(
                            avatar = '', 
                            display_name = '', 
                            email = '', 
                            kind = '', 
                            name = '', ), 
                        spec = halo_client.models.reply_spec.ReplySpec(
                            allow_notification = True, 
                            approved = True, 
                            approved_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            comment_name = '0', 
                            content = '0', 
                            creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            hidden = True, 
                            ip_address = '', 
                            owner = halo_client.models.comment_owner.CommentOwner(
                                display_name = '', 
                                kind = '0', 
                                name = '', ), 
                            priority = 56, 
                            quote_reply = '', 
                            raw = '0', 
                            top = True, 
                            user_agent = '', ), 
                        stats = halo_client.models.comment_stats_vo.CommentStatsVo(
                            upvote = 56, ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56,
        )
        """

    def testReplyVoList(self):
        """Test ReplyVoList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
