# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.personal_access_token_v1alpha1_api import PersonalAccessTokenV1alpha1Api


class TestPersonalAccessTokenV1alpha1Api(unittest.TestCase):
    """PersonalAccessTokenV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = PersonalAccessTokenV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_personal_access_token(self) -> None:
        """Test case for create_personal_access_token

        """
        pass

    def test_delete_personal_access_token(self) -> None:
        """Test case for delete_personal_access_token

        """
        pass

    def test_get_personal_access_token(self) -> None:
        """Test case for get_personal_access_token

        """
        pass

    def test_list_personal_access_token(self) -> None:
        """Test case for list_personal_access_token

        """
        pass

    def test_patch_personal_access_token(self) -> None:
        """Test case for patch_personal_access_token

        """
        pass

    def test_update_personal_access_token(self) -> None:
        """Test case for update_personal_access_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
