# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.subscription import Subscription

class TestSubscription(unittest.TestCase):
    """Subscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subscription:
        """Test Subscription
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subscription`
        """
        model = Subscription()
        if include_optional:
            return Subscription(
                api_version = '',
                kind = '',
                metadata = halo_client.models.metadata.Metadata(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    name = '', 
                    version = 56, ),
                spec = halo_client.models.subscription_spec.SubscriptionSpec(
                    disabled = True, 
                    reason = halo_client.models.interest_reason.InterestReason(
                        expression = '', 
                        reason_type = '', 
                        subject = halo_client.models.interest_reason_subject.InterestReasonSubject(
                            api_version = '0', 
                            kind = '0', 
                            name = '', ), ), 
                    subscriber = halo_client.models.subscription_subscriber.SubscriptionSubscriber(
                        name = '0', ), 
                    unsubscribe_token = '', )
            )
        else:
            return Subscription(
                api_version = '',
                kind = '',
                metadata = halo_client.models.metadata.Metadata(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    name = '', 
                    version = 56, ),
        )
        """

    def testSubscription(self):
        """Test Subscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
