# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.plugin_v1alpha1_public_api import PluginV1alpha1PublicApi


class TestPluginV1alpha1PublicApi(unittest.TestCase):
    """PluginV1alpha1PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PluginV1alpha1PublicApi()

    def tearDown(self) -> None:
        pass

    def test_query_plugin_available_by_name(self) -> None:
        """Test case for query_plugin_available_by_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
