# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.annotation_setting_v1alpha1_api import AnnotationSettingV1alpha1Api


class TestAnnotationSettingV1alpha1Api(unittest.TestCase):
    """AnnotationSettingV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AnnotationSettingV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_annotation_setting(self) -> None:
        """Test case for create_annotation_setting

        """
        pass

    def test_delete_annotation_setting(self) -> None:
        """Test case for delete_annotation_setting

        """
        pass

    def test_get_annotation_setting(self) -> None:
        """Test case for get_annotation_setting

        """
        pass

    def test_list_annotation_setting(self) -> None:
        """Test case for list_annotation_setting

        """
        pass

    def test_patch_annotation_setting(self) -> None:
        """Test case for patch_annotation_setting

        """
        pass

    def test_update_annotation_setting(self) -> None:
        """Test case for update_annotation_setting

        """
        pass


if __name__ == '__main__':
    unittest.main()
