# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.role_binding_list import RoleBindingList

class TestRoleBindingList(unittest.TestCase):
    """RoleBindingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoleBindingList:
        """Test RoleBindingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoleBindingList`
        """
        model = RoleBindingList()
        if include_optional:
            return RoleBindingList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.role_binding.RoleBinding(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        role_ref = halo_client.models.role_ref.RoleRef(
                            api_group = '', 
                            kind = '', 
                            name = '', ), 
                        subjects = [
                            halo_client.models.subject.Subject(
                                api_group = '', 
                                kind = '', 
                                name = '', )
                            ], )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56
            )
        else:
            return RoleBindingList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.role_binding.RoleBinding(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        role_ref = halo_client.models.role_ref.RoleRef(
                            api_group = '', 
                            kind = '', 
                            name = '', ), 
                        subjects = [
                            halo_client.models.subject.Subject(
                                api_group = '', 
                                kind = '', 
                                name = '', )
                            ], )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56,
        )
        """

    def testRoleBindingList(self):
        """Test RoleBindingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
