# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.listed_comment_list import ListedCommentList

class TestListedCommentList(unittest.TestCase):
    """ListedCommentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListedCommentList:
        """Test ListedCommentList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListedCommentList`
        """
        model = ListedCommentList()
        if include_optional:
            return ListedCommentList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.listed_comment.ListedComment(
                        comment = halo_client.models.comment.Comment(
                            api_version = '', 
                            kind = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                annotations = {
                                    'key' : ''
                                    }, 
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                finalizers = [
                                    ''
                                    ], 
                                generate_name = '', 
                                labels = {
                                    'key' : ''
                                    }, 
                                name = '', 
                                version = 56, ), 
                            spec = halo_client.models.comment_spec.CommentSpec(
                                allow_notification = True, 
                                approved = True, 
                                approved_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                content = '0', 
                                creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                hidden = True, 
                                ip_address = '', 
                                last_read_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                owner = halo_client.models.comment_owner.CommentOwner(
                                    display_name = '', 
                                    kind = '0', 
                                    name = '', ), 
                                priority = 56, 
                                raw = '0', 
                                subject_ref = halo_client.models.ref.Ref(
                                    group = '', 
                                    kind = '', 
                                    name = '', 
                                    version = '', ), 
                                top = True, 
                                user_agent = '', ), 
                            status = halo_client.models.comment_status.CommentStatus(
                                has_new_reply = True, 
                                last_reply_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                observed_version = 56, 
                                reply_count = 56, 
                                unread_reply_count = 56, 
                                visible_reply_count = 56, ), ), 
                        owner = halo_client.models.owner_info.OwnerInfo(
                            avatar = '', 
                            display_name = '', 
                            email = '', 
                            kind = '', 
                            name = '', ), 
                        stats = halo_client.models.comment_stats.CommentStats(
                            upvote = 56, ), 
                        subject = halo_client.models.extension.Extension(
                            api_version = '', 
                            kind = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generate_name = '', 
                                name = '', 
                                version = 56, ), ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56
            )
        else:
            return ListedCommentList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.listed_comment.ListedComment(
                        comment = halo_client.models.comment.Comment(
                            api_version = '', 
                            kind = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                annotations = {
                                    'key' : ''
                                    }, 
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                finalizers = [
                                    ''
                                    ], 
                                generate_name = '', 
                                labels = {
                                    'key' : ''
                                    }, 
                                name = '', 
                                version = 56, ), 
                            spec = halo_client.models.comment_spec.CommentSpec(
                                allow_notification = True, 
                                approved = True, 
                                approved_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                content = '0', 
                                creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                hidden = True, 
                                ip_address = '', 
                                last_read_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                owner = halo_client.models.comment_owner.CommentOwner(
                                    display_name = '', 
                                    kind = '0', 
                                    name = '', ), 
                                priority = 56, 
                                raw = '0', 
                                subject_ref = halo_client.models.ref.Ref(
                                    group = '', 
                                    kind = '', 
                                    name = '', 
                                    version = '', ), 
                                top = True, 
                                user_agent = '', ), 
                            status = halo_client.models.comment_status.CommentStatus(
                                has_new_reply = True, 
                                last_reply_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                observed_version = 56, 
                                reply_count = 56, 
                                unread_reply_count = 56, 
                                visible_reply_count = 56, ), ), 
                        owner = halo_client.models.owner_info.OwnerInfo(
                            avatar = '', 
                            display_name = '', 
                            email = '', 
                            kind = '', 
                            name = '', ), 
                        stats = halo_client.models.comment_stats.CommentStats(
                            upvote = 56, ), 
                        subject = halo_client.models.extension.Extension(
                            api_version = '', 
                            kind = '', 
                            metadata = halo_client.models.metadata.Metadata(
                                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generate_name = '', 
                                name = '', 
                                version = 56, ), ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56,
        )
        """

    def testListedCommentList(self):
        """Test ListedCommentList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
