# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.reason_attributes import ReasonAttributes

class TestReasonAttributes(unittest.TestCase):
    """ReasonAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReasonAttributes:
        """Test ReasonAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReasonAttributes`
        """
        model = ReasonAttributes()
        if include_optional:
            return ReasonAttributes(
                empty = True
            )
        else:
            return ReasonAttributes(
        )
        """

    def testReasonAttributes(self):
        """Test ReasonAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
