# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.user import User

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()
        if include_optional:
            return User(
                api_version = '',
                kind = '',
                metadata = halo_client.models.metadata.Metadata(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    name = '', 
                    version = 56, ),
                spec = halo_client.models.user_spec.UserSpec(
                    avatar = '', 
                    bio = '', 
                    disabled = True, 
                    display_name = '', 
                    email = '', 
                    email_verified = True, 
                    login_history_limit = 56, 
                    password = '', 
                    phone = '', 
                    registered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    totp_encrypted_secret = '', 
                    two_factor_auth_enabled = True, ),
                status = halo_client.models.user_status.UserStatus(
                    last_login_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    login_histories = [
                        halo_client.models.login_history.LoginHistory(
                            login_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            reason = '', 
                            source_ip = '', 
                            successful = True, 
                            user_agent = '', )
                        ], 
                    permalink = '', )
            )
        else:
            return User(
                api_version = '',
                kind = '',
                metadata = halo_client.models.metadata.Metadata(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    name = '', 
                    version = 56, ),
                spec = halo_client.models.user_spec.UserSpec(
                    avatar = '', 
                    bio = '', 
                    disabled = True, 
                    display_name = '', 
                    email = '', 
                    email_verified = True, 
                    login_history_limit = 56, 
                    password = '', 
                    phone = '', 
                    registered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    totp_encrypted_secret = '', 
                    two_factor_auth_enabled = True, ),
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
