# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.notification_v1alpha1_public_api import NotificationV1alpha1PublicApi


class TestNotificationV1alpha1PublicApi(unittest.TestCase):
    """NotificationV1alpha1PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationV1alpha1PublicApi()

    def tearDown(self) -> None:
        pass

    def test_unsubscribe(self) -> None:
        """Test case for unsubscribe

        """
        pass


if __name__ == '__main__':
    unittest.main()
