# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.policy_list import PolicyList

class TestPolicyList(unittest.TestCase):
    """PolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyList:
        """Test PolicyList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyList`
        """
        model = PolicyList()
        if include_optional:
            return PolicyList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.policy.Policy(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        spec = halo_client.models.policy_spec.PolicySpec(
                            config_map_name = '', 
                            display_name = '', 
                            template_name = '', ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56
            )
        else:
            return PolicyList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.policy.Policy(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        spec = halo_client.models.policy_spec.PolicySpec(
                            config_map_name = '', 
                            display_name = '', 
                            template_name = '', ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56,
        )
        """

    def testPolicyList(self):
        """Test PolicyList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
