# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.subscription_spec import SubscriptionSpec

class TestSubscriptionSpec(unittest.TestCase):
    """SubscriptionSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionSpec:
        """Test SubscriptionSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionSpec`
        """
        model = SubscriptionSpec()
        if include_optional:
            return SubscriptionSpec(
                disabled = True,
                reason = halo_client.models.interest_reason.InterestReason(
                    expression = '', 
                    reason_type = '', 
                    subject = halo_client.models.interest_reason_subject.InterestReasonSubject(
                        api_version = '0', 
                        kind = '0', 
                        name = '', ), ),
                subscriber = halo_client.models.subscription_subscriber.SubscriptionSubscriber(
                    name = '0', ),
                unsubscribe_token = ''
            )
        else:
            return SubscriptionSpec(
                reason = halo_client.models.interest_reason.InterestReason(
                    expression = '', 
                    reason_type = '', 
                    subject = halo_client.models.interest_reason_subject.InterestReasonSubject(
                        api_version = '0', 
                        kind = '0', 
                        name = '', ), ),
                subscriber = halo_client.models.subscription_subscriber.SubscriptionSubscriber(
                    name = '0', ),
                unsubscribe_token = '',
        )
        """

    def testSubscriptionSpec(self):
        """Test SubscriptionSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
