# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.system_v1alpha1_public_api import SystemV1alpha1PublicApi


class TestSystemV1alpha1PublicApi(unittest.TestCase):
    """SystemV1alpha1PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemV1alpha1PublicApi()

    def tearDown(self) -> None:
        pass

    def test_jump_to_setup_page(self) -> None:
        """Test case for jump_to_setup_page

        """
        pass

    def test_query_stats(self) -> None:
        """Test case for query_stats

        """
        pass

    def test_setup_system(self) -> None:
        """Test case for setup_system

        """
        pass


if __name__ == '__main__':
    unittest.main()
