# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.reverse_proxy_v1alpha1_api import ReverseProxyV1alpha1Api


class TestReverseProxyV1alpha1Api(unittest.TestCase):
    """ReverseProxyV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ReverseProxyV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_reverse_proxy(self) -> None:
        """Test case for create_reverse_proxy

        """
        pass

    def test_delete_reverse_proxy(self) -> None:
        """Test case for delete_reverse_proxy

        """
        pass

    def test_get_reverse_proxy(self) -> None:
        """Test case for get_reverse_proxy

        """
        pass

    def test_list_reverse_proxy(self) -> None:
        """Test case for list_reverse_proxy

        """
        pass

    def test_patch_reverse_proxy(self) -> None:
        """Test case for patch_reverse_proxy

        """
        pass

    def test_update_reverse_proxy(self) -> None:
        """Test case for update_reverse_proxy

        """
        pass


if __name__ == '__main__':
    unittest.main()
