# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.extension_definition_v1alpha1_api import ExtensionDefinitionV1alpha1Api


class TestExtensionDefinitionV1alpha1Api(unittest.TestCase):
    """ExtensionDefinitionV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ExtensionDefinitionV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_extension_definition(self) -> None:
        """Test case for create_extension_definition

        """
        pass

    def test_delete_extension_definition(self) -> None:
        """Test case for delete_extension_definition

        """
        pass

    def test_get_extension_definition(self) -> None:
        """Test case for get_extension_definition

        """
        pass

    def test_list_extension_definition(self) -> None:
        """Test case for list_extension_definition

        """
        pass

    def test_patch_extension_definition(self) -> None:
        """Test case for patch_extension_definition

        """
        pass

    def test_update_extension_definition(self) -> None:
        """Test case for update_extension_definition

        """
        pass


if __name__ == '__main__':
    unittest.main()
