# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.dashboard_stats import DashboardStats

class TestDashboardStats(unittest.TestCase):
    """DashboardStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardStats:
        """Test DashboardStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardStats`
        """
        model = DashboardStats()
        if include_optional:
            return DashboardStats(
                approved_comments = 56,
                comments = 56,
                posts = 56,
                upvotes = 56,
                users = 56,
                visits = 56
            )
        else:
            return DashboardStats(
        )
        """

    def testDashboardStats(self):
        """Test DashboardStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
