# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.snapshot_v1alpha1_uc_api import SnapshotV1alpha1UcApi


class TestSnapshotV1alpha1UcApi(unittest.TestCase):
    """SnapshotV1alpha1UcApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnapshotV1alpha1UcApi()

    def tearDown(self) -> None:
        pass

    def test_get_snapshot_for_post(self) -> None:
        """Test case for get_snapshot_for_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
