# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.reason_v1alpha1_api import ReasonV1alpha1Api


class TestReasonV1alpha1Api(unittest.TestCase):
    """ReasonV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ReasonV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_reason(self) -> None:
        """Test case for create_reason

        """
        pass

    def test_delete_reason(self) -> None:
        """Test case for delete_reason

        """
        pass

    def test_get_reason(self) -> None:
        """Test case for get_reason

        """
        pass

    def test_list_reason(self) -> None:
        """Test case for list_reason

        """
        pass

    def test_patch_reason(self) -> None:
        """Test case for patch_reason

        """
        pass

    def test_update_reason(self) -> None:
        """Test case for update_reason

        """
        pass


if __name__ == '__main__':
    unittest.main()
