# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.user_v1alpha1_api import UserV1alpha1Api


class TestUserV1alpha1Api(unittest.TestCase):
    """UserV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = UserV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        """
        pass

    def test_list_user(self) -> None:
        """Test case for list_user

        """
        pass

    def test_patch_user(self) -> None:
        """Test case for patch_user

        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
