# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.backup_v1alpha1_api import BackupV1alpha1Api


class TestBackupV1alpha1Api(unittest.TestCase):
    """BackupV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = BackupV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_backup(self) -> None:
        """Test case for create_backup

        """
        pass

    def test_delete_backup(self) -> None:
        """Test case for delete_backup

        """
        pass

    def test_get_backup(self) -> None:
        """Test case for get_backup

        """
        pass

    def test_list_backup(self) -> None:
        """Test case for list_backup

        """
        pass

    def test_patch_backup(self) -> None:
        """Test case for patch_backup

        """
        pass

    def test_update_backup(self) -> None:
        """Test case for update_backup

        """
        pass


if __name__ == '__main__':
    unittest.main()
