# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.content_update_param import ContentUpdateParam

class TestContentUpdateParam(unittest.TestCase):
    """ContentUpdateParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentUpdateParam:
        """Test ContentUpdateParam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentUpdateParam`
        """
        model = ContentUpdateParam()
        if include_optional:
            return ContentUpdateParam(
                content = '',
                raw = '',
                raw_type = '',
                version = 56
            )
        else:
            return ContentUpdateParam(
                content = '',
                raw = '',
                raw_type = '',
        )
        """

    def testContentUpdateParam(self):
        """Test ContentUpdateParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
