# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.auth_provider_v1alpha1_api import AuthProviderV1alpha1Api


class TestAuthProviderV1alpha1Api(unittest.TestCase):
    """AuthProviderV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthProviderV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_auth_provider(self) -> None:
        """Test case for create_auth_provider

        """
        pass

    def test_delete_auth_provider(self) -> None:
        """Test case for delete_auth_provider

        """
        pass

    def test_get_auth_provider(self) -> None:
        """Test case for get_auth_provider

        """
        pass

    def test_list_auth_provider(self) -> None:
        """Test case for list_auth_provider

        """
        pass

    def test_patch_auth_provider(self) -> None:
        """Test case for patch_auth_provider

        """
        pass

    def test_update_auth_provider(self) -> None:
        """Test case for update_auth_provider

        """
        pass


if __name__ == '__main__':
    unittest.main()
