# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.menu_item_v1alpha1_api import MenuItemV1alpha1Api


class TestMenuItemV1alpha1Api(unittest.TestCase):
    """MenuItemV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = MenuItemV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_menu_item(self) -> None:
        """Test case for create_menu_item

        """
        pass

    def test_delete_menu_item(self) -> None:
        """Test case for delete_menu_item

        """
        pass

    def test_get_menu_item(self) -> None:
        """Test case for get_menu_item

        """
        pass

    def test_list_menu_item(self) -> None:
        """Test case for list_menu_item

        """
        pass

    def test_patch_menu_item(self) -> None:
        """Test case for patch_menu_item

        """
        pass

    def test_update_menu_item(self) -> None:
        """Test case for update_menu_item

        """
        pass


if __name__ == '__main__':
    unittest.main()
