# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.metrics_v1alpha1_public_api import MetricsV1alpha1PublicApi


class TestMetricsV1alpha1PublicApi(unittest.TestCase):
    """MetricsV1alpha1PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsV1alpha1PublicApi()

    def tearDown(self) -> None:
        pass

    def test_count(self) -> None:
        """Test case for count

        """
        pass

    def test_downvote(self) -> None:
        """Test case for downvote

        """
        pass

    def test_upvote(self) -> None:
        """Test case for upvote

        """
        pass


if __name__ == '__main__':
    unittest.main()
