# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.snapshot_list import SnapshotList

class TestSnapshotList(unittest.TestCase):
    """SnapshotList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnapshotList:
        """Test SnapshotList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnapshotList`
        """
        model = SnapshotList()
        if include_optional:
            return SnapshotList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.snapshot.Snapshot(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        spec = halo_client.models.snap_shot_spec.SnapShotSpec(
                            content_patch = '', 
                            contributors = [
                                ''
                                ], 
                            last_modify_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            owner = '0', 
                            parent_snapshot_name = '', 
                            raw_patch = '', 
                            raw_type = '0', 
                            subject_ref = halo_client.models.ref.Ref(
                                group = '', 
                                kind = '', 
                                name = '', 
                                version = '', ), ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56
            )
        else:
            return SnapshotList(
                first = True,
                has_next = True,
                has_previous = True,
                items = [
                    halo_client.models.snapshot.Snapshot(
                        api_version = '', 
                        kind = '', 
                        metadata = halo_client.models.metadata.Metadata(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            name = '', 
                            version = 56, ), 
                        spec = halo_client.models.snap_shot_spec.SnapShotSpec(
                            content_patch = '', 
                            contributors = [
                                ''
                                ], 
                            last_modify_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            owner = '0', 
                            parent_snapshot_name = '', 
                            raw_patch = '', 
                            raw_type = '0', 
                            subject_ref = halo_client.models.ref.Ref(
                                group = '', 
                                kind = '', 
                                name = '', 
                                version = '', ), ), )
                    ],
                last = True,
                page = 56,
                size = 56,
                total = 56,
                total_pages = 56,
        )
        """

    def testSnapshotList(self):
        """Test SnapshotList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
