# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.thumbnail_v1alpha1_api import ThumbnailV1alpha1Api


class TestThumbnailV1alpha1Api(unittest.TestCase):
    """ThumbnailV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ThumbnailV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_thumbnail(self) -> None:
        """Test case for create_thumbnail

        """
        pass

    def test_delete_thumbnail(self) -> None:
        """Test case for delete_thumbnail

        """
        pass

    def test_get_thumbnail(self) -> None:
        """Test case for get_thumbnail

        """
        pass

    def test_list_thumbnail(self) -> None:
        """Test case for list_thumbnail

        """
        pass

    def test_patch_thumbnail(self) -> None:
        """Test case for patch_thumbnail

        """
        pass

    def test_update_thumbnail(self) -> None:
        """Test case for update_thumbnail

        """
        pass


if __name__ == '__main__':
    unittest.main()
