# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.single_page_v1alpha1_console_api import SinglePageV1alpha1ConsoleApi


class TestSinglePageV1alpha1ConsoleApi(unittest.TestCase):
    """SinglePageV1alpha1ConsoleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SinglePageV1alpha1ConsoleApi()

    def tearDown(self) -> None:
        pass

    def test_delete_single_page_content(self) -> None:
        """Test case for delete_single_page_content

        """
        pass

    def test_draft_single_page(self) -> None:
        """Test case for draft_single_page

        """
        pass

    def test_fetch_single_page_content(self) -> None:
        """Test case for fetch_single_page_content

        """
        pass

    def test_fetch_single_page_head_content(self) -> None:
        """Test case for fetch_single_page_head_content

        """
        pass

    def test_fetch_single_page_release_content(self) -> None:
        """Test case for fetch_single_page_release_content

        """
        pass

    def test_list_single_page_snapshots(self) -> None:
        """Test case for list_single_page_snapshots

        """
        pass

    def test_list_single_pages(self) -> None:
        """Test case for list_single_pages

        """
        pass

    def test_publish_single_page(self) -> None:
        """Test case for publish_single_page

        """
        pass

    def test_revert_to_specified_snapshot_for_single_page(self) -> None:
        """Test case for revert_to_specified_snapshot_for_single_page

        """
        pass

    def test_update_draft_single_page(self) -> None:
        """Test case for update_draft_single_page

        """
        pass

    def test_update_single_page_content(self) -> None:
        """Test case for update_single_page_content

        """
        pass


if __name__ == '__main__':
    unittest.main()
