# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.policy_template_v1alpha1_api import PolicyTemplateV1alpha1Api


class TestPolicyTemplateV1alpha1Api(unittest.TestCase):
    """PolicyTemplateV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyTemplateV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_policy_template(self) -> None:
        """Test case for create_policy_template

        """
        pass

    def test_delete_policy_template(self) -> None:
        """Test case for delete_policy_template

        """
        pass

    def test_get_policy_template(self) -> None:
        """Test case for get_policy_template

        """
        pass

    def test_list_policy_template(self) -> None:
        """Test case for list_policy_template

        """
        pass

    def test_patch_policy_template(self) -> None:
        """Test case for patch_policy_template

        """
        pass

    def test_update_policy_template(self) -> None:
        """Test case for update_policy_template

        """
        pass


if __name__ == '__main__':
    unittest.main()
