# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.notification_spec import NotificationSpec

class TestNotificationSpec(unittest.TestCase):
    """NotificationSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationSpec:
        """Test NotificationSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationSpec`
        """
        model = NotificationSpec()
        if include_optional:
            return NotificationSpec(
                html_content = '',
                last_read_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                raw_content = '',
                reason = '0',
                recipient = '0',
                title = '0',
                unread = True
            )
        else:
            return NotificationSpec(
                html_content = '',
                raw_content = '',
                reason = '0',
                recipient = '0',
                title = '0',
        )
        """

    def testNotificationSpec(self):
        """Test NotificationSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
