# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.post_v1alpha1_uc_api import PostV1alpha1UcApi


class TestPostV1alpha1UcApi(unittest.TestCase):
    """PostV1alpha1UcApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostV1alpha1UcApi()

    def tearDown(self) -> None:
        pass

    def test_create_my_post(self) -> None:
        """Test case for create_my_post

        """
        pass

    def test_get_my_post(self) -> None:
        """Test case for get_my_post

        """
        pass

    def test_get_my_post_draft(self) -> None:
        """Test case for get_my_post_draft

        """
        pass

    def test_list_my_posts(self) -> None:
        """Test case for list_my_posts

        """
        pass

    def test_publish_my_post(self) -> None:
        """Test case for publish_my_post

        """
        pass

    def test_recycle_my_post(self) -> None:
        """Test case for recycle_my_post

        """
        pass

    def test_unpublish_my_post(self) -> None:
        """Test case for unpublish_my_post

        """
        pass

    def test_update_my_post(self) -> None:
        """Test case for update_my_post

        """
        pass

    def test_update_my_post_draft(self) -> None:
        """Test case for update_my_post_draft

        """
        pass


if __name__ == '__main__':
    unittest.main()
