# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.attachment_v1alpha1_api import AttachmentV1alpha1Api


class TestAttachmentV1alpha1Api(unittest.TestCase):
    """AttachmentV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AttachmentV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_attachment(self) -> None:
        """Test case for create_attachment

        """
        pass

    def test_delete_attachment(self) -> None:
        """Test case for delete_attachment

        """
        pass

    def test_get_attachment(self) -> None:
        """Test case for get_attachment

        """
        pass

    def test_list_attachment(self) -> None:
        """Test case for list_attachment

        """
        pass

    def test_patch_attachment(self) -> None:
        """Test case for patch_attachment

        """
        pass

    def test_update_attachment(self) -> None:
        """Test case for update_attachment

        """
        pass


if __name__ == '__main__':
    unittest.main()
