# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.policy_alpha1_console_api import PolicyAlpha1ConsoleApi


class TestPolicyAlpha1ConsoleApi(unittest.TestCase):
    """PolicyAlpha1ConsoleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyAlpha1ConsoleApi()

    def tearDown(self) -> None:
        pass

    def test_get_policy_config_by_group(self) -> None:
        """Test case for get_policy_config_by_group

        """
        pass

    def test_update_policy_config_by_group(self) -> None:
        """Test case for update_policy_config_by_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
