# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.setting_v1alpha1_api import SettingV1alpha1Api


class TestSettingV1alpha1Api(unittest.TestCase):
    """SettingV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_setting(self) -> None:
        """Test case for create_setting

        """
        pass

    def test_delete_setting(self) -> None:
        """Test case for delete_setting

        """
        pass

    def test_get_setting(self) -> None:
        """Test case for get_setting

        """
        pass

    def test_list_setting(self) -> None:
        """Test case for list_setting

        """
        pass

    def test_patch_setting(self) -> None:
        """Test case for patch_setting

        """
        pass

    def test_update_setting(self) -> None:
        """Test case for update_setting

        """
        pass


if __name__ == '__main__':
    unittest.main()
