# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.category_spec import CategorySpec

class TestCategorySpec(unittest.TestCase):
    """CategorySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategorySpec:
        """Test CategorySpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategorySpec`
        """
        model = CategorySpec()
        if include_optional:
            return CategorySpec(
                children = [
                    ''
                    ],
                cover = '',
                description = '',
                display_name = '0',
                hide_from_list = True,
                post_template = '',
                prevent_parent_post_cascade_query = True,
                priority = 56,
                slug = '0',
                template = ''
            )
        else:
            return CategorySpec(
                display_name = '0',
                priority = 56,
                slug = '0',
        )
        """

    def testCategorySpec(self):
        """Test CategorySpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
