# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.halo_document import HaloDocument

class TestHaloDocument(unittest.TestCase):
    """HaloDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HaloDocument:
        """Test HaloDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HaloDocument`
        """
        model = HaloDocument()
        if include_optional:
            return HaloDocument(
                annotations = {
                    'key' : ''
                    },
                categories = [
                    ''
                    ],
                content = '0',
                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                exposed = True,
                id = '0',
                metadata_name = '0',
                owner_name = '0',
                permalink = '0',
                published = True,
                recycled = True,
                tags = [
                    ''
                    ],
                title = '0',
                type = '0',
                update_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return HaloDocument(
                content = '0',
                id = '0',
                metadata_name = '0',
                owner_name = '0',
                permalink = '0',
                title = '0',
                type = '0',
        )
        """

    def testHaloDocument(self):
        """Test HaloDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
