# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.models.reason_selector import ReasonSelector

class TestReasonSelector(unittest.TestCase):
    """ReasonSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReasonSelector:
        """Test ReasonSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReasonSelector`
        """
        model = ReasonSelector()
        if include_optional:
            return ReasonSelector(
                language = 'default',
                reason_type = '0'
            )
        else:
            return ReasonSelector(
                language = 'default',
                reason_type = '0',
        )
        """

    def testReasonSelector(self):
        """Test ReasonSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
