# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.plugin_v1alpha1_api import PluginV1alpha1Api


class TestPluginV1alpha1Api(unittest.TestCase):
    """PluginV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = PluginV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_plugin(self) -> None:
        """Test case for create_plugin

        """
        pass

    def test_delete_plugin(self) -> None:
        """Test case for delete_plugin

        """
        pass

    def test_get_plugin(self) -> None:
        """Test case for get_plugin

        """
        pass

    def test_list_plugin(self) -> None:
        """Test case for list_plugin

        """
        pass

    def test_patch_plugin(self) -> None:
        """Test case for patch_plugin

        """
        pass

    def test_update_plugin(self) -> None:
        """Test case for update_plugin

        """
        pass


if __name__ == '__main__':
    unittest.main()
