# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from halo_client.api.two_factor_auth_v1alpha1_uc_api import TwoFactorAuthV1alpha1UcApi


class TestTwoFactorAuthV1alpha1UcApi(unittest.TestCase):
    """TwoFactorAuthV1alpha1UcApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TwoFactorAuthV1alpha1UcApi()

    def tearDown(self) -> None:
        pass

    def test_configurer_totp(self) -> None:
        """Test case for configurer_totp

        """
        pass

    def test_delete_totp(self) -> None:
        """Test case for delete_totp

        """
        pass

    def test_disable_two_factor(self) -> None:
        """Test case for disable_two_factor

        """
        pass

    def test_enable_two_factor(self) -> None:
        """Test case for enable_two_factor

        """
        pass

    def test_get_totp_auth_link(self) -> None:
        """Test case for get_totp_auth_link

        """
        pass

    def test_get_two_factor_authentication_settings(self) -> None:
        """Test case for get_two_factor_authentication_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
