# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CategorySpec(BaseModel):
    """
    CategorySpec
    """ # noqa: E501
    children: Optional[List[StrictStr]] = None
    cover: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    display_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="displayName")
    hide_from_list: Optional[StrictBool] = Field(default=None, description="<p>Whether to hide the category from the category list.</p>  <p>When set to true, the category including its subcategories and related posts will  not be displayed in the category list, but it can still be accessed by permalink.</p>  <p>Limitation: It only takes effect on the theme-side categorized list and it only  allows to be set to true on the first level(root node) of categories.</p>", alias="hideFromList")
    post_template: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="<p>Used to specify the template for the posts associated with the category.</p>  <p>The priority is not as high as that of the post.</p>  <p>If the post also specifies a template, the post's template will prevail.</p>", alias="postTemplate")
    prevent_parent_post_cascade_query: Optional[StrictBool] = Field(default=None, description="<p>if a category is queried for related posts, the default behavior is to  query all posts under the category including its subcategories, but if this field is  set to true, cascade query behavior will be terminated here.</p>  <p>For example, if a category has subcategories A and B, and A has subcategories C and  D and C marked this field as true, when querying posts under A category,all posts under A  and B will be queried, but C and D will not be queried.</p>", alias="preventParentPostCascadeQuery")
    priority: StrictInt
    slug: Annotated[str, Field(min_length=1, strict=True)]
    template: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    __properties: ClassVar[List[str]] = ["children", "cover", "description", "displayName", "hideFromList", "postTemplate", "preventParentPostCascadeQuery", "priority", "slug", "template"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CategorySpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CategorySpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "children": obj.get("children"),
            "cover": obj.get("cover"),
            "description": obj.get("description"),
            "displayName": obj.get("displayName"),
            "hideFromList": obj.get("hideFromList"),
            "postTemplate": obj.get("postTemplate"),
            "preventParentPostCascadeQuery": obj.get("preventParentPostCascadeQuery"),
            "priority": obj.get("priority") if obj.get("priority") is not None else 0,
            "slug": obj.get("slug"),
            "template": obj.get("template")
        })
        return _obj


