# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from halo_client.models.template_descriptor import TemplateDescriptor
from typing import Optional, Set
from typing_extensions import Self

class CustomTemplates(BaseModel):
    """
    CustomTemplates
    """ # noqa: E501
    category: Optional[List[TemplateDescriptor]] = None
    page: Optional[List[TemplateDescriptor]] = None
    post: Optional[List[TemplateDescriptor]] = None
    __properties: ClassVar[List[str]] = ["category", "page", "post"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomTemplates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in category (list)
        _items = []
        if self.category:
            for _item_category in self.category:
                if _item_category:
                    _items.append(_item_category.to_dict())
            _dict['category'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in page (list)
        _items = []
        if self.page:
            for _item_page in self.page:
                if _item_page:
                    _items.append(_item_page.to_dict())
            _dict['page'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in post (list)
        _items = []
        if self.post:
            for _item_post in self.post:
                if _item_post:
                    _items.append(_item_post.to_dict())
            _dict['post'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomTemplates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "category": [TemplateDescriptor.from_dict(_item) for _item in obj["category"]] if obj.get("category") is not None else None,
            "page": [TemplateDescriptor.from_dict(_item) for _item in obj["page"]] if obj.get("page") is not None else None,
            "post": [TemplateDescriptor.from_dict(_item) for _item in obj["post"]] if obj.get("post") is not None else None
        })
        return _obj


