# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from halo_client.models.ref import Ref
from typing import Optional, Set
from typing_extensions import Self

class MenuItemSpec(BaseModel):
    """
    MenuItemSpec
    """ # noqa: E501
    children: Optional[List[StrictStr]] = Field(default=None, description="Children of this menu item")
    display_name: Optional[StrictStr] = Field(default=None, description="The display name of menu item.", alias="displayName")
    href: Optional[StrictStr] = Field(default=None, description="The href of this menu item.")
    priority: Optional[StrictInt] = Field(default=None, description="The priority is for ordering.")
    target: Optional[StrictStr] = Field(default=None, description="The <a> target attribute of this menu item.")
    target_ref: Optional[Ref] = Field(default=None, alias="targetRef")
    __properties: ClassVar[List[str]] = ["children", "displayName", "href", "priority", "target", "targetRef"]

    @field_validator('target')
    def target_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['_blank', '_self', '_parent', '_top']):
            raise ValueError("must be one of enum values ('_blank', '_self', '_parent', '_top')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MenuItemSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of target_ref
        if self.target_ref:
            _dict['targetRef'] = self.target_ref.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MenuItemSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "children": obj.get("children"),
            "displayName": obj.get("displayName"),
            "href": obj.get("href"),
            "priority": obj.get("priority"),
            "target": obj.get("target"),
            "targetRef": Ref.from_dict(obj["targetRef"]) if obj.get("targetRef") is not None else None
        })
        return _obj


