# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PostStatus(BaseModel):
    """
    PostStatus
    """ # noqa: E501
    comments_count: Optional[StrictInt] = Field(default=None, alias="commentsCount")
    conditions: Optional[List[Condition]] = None
    contributors: Optional[List[StrictStr]] = None
    excerpt: Optional[StrictStr] = None
    hide_from_list: Optional[StrictBool] = Field(default=None, description="see {@link Category.CategorySpec#isHideFromList Category.CategorySpec#isHideFromList()}.", alias="hideFromList")
    in_progress: Optional[StrictBool] = Field(default=None, alias="inProgress")
    last_modify_time: Optional[datetime] = Field(default=None, alias="lastModifyTime")
    observed_version: Optional[StrictInt] = Field(default=None, alias="observedVersion")
    permalink: Optional[StrictStr] = None
    phase: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["commentsCount", "conditions", "contributors", "excerpt", "hideFromList", "inProgress", "lastModifyTime", "observedVersion", "permalink", "phase"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commentsCount": obj.get("commentsCount"),
            "contributors": obj.get("contributors"),
            "excerpt": obj.get("excerpt"),
            "hideFromList": obj.get("hideFromList"),
            "inProgress": obj.get("inProgress"),
            "lastModifyTime": obj.get("lastModifyTime"),
            "observedVersion": obj.get("observedVersion"),
            "permalink": obj.get("permalink"),
            "phase": obj.get("phase")
        })
        return _obj


