# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from halo_client.models.comment_email_owner import CommentEmailOwner
from typing import Optional, Set
from typing_extensions import Self

class ReplyRequest(BaseModel):
    """
    A request parameter object for {@link Reply Reply}.
    """ # noqa: E501
    allow_notification: Optional[StrictBool] = Field(default=False, alias="allowNotification")
    content: Annotated[str, Field(min_length=1, strict=True)]
    hidden: Optional[StrictBool] = False
    owner: Optional[CommentEmailOwner] = None
    quote_reply: Optional[StrictStr] = Field(default=None, alias="quoteReply")
    raw: Annotated[str, Field(min_length=1, strict=True)]
    __properties: ClassVar[List[str]] = ["allowNotification", "content", "hidden", "owner", "quoteReply", "raw"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowNotification": obj.get("allowNotification") if obj.get("allowNotification") is not None else False,
            "content": obj.get("content"),
            "hidden": obj.get("hidden") if obj.get("hidden") is not None else False,
            "owner": CommentEmailOwner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "quoteReply": obj.get("quoteReply"),
            "raw": obj.get("raw")
        })
        return _obj


