# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.21.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SearchOption(BaseModel):
    """
    Search option. It is used to control search behavior.
    """ # noqa: E501
    annotations: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional annotations for extending search option by other search engines.")
    filter_exposed: Optional[StrictBool] = Field(default=None, description="Whether to filter exposed content. If null, it will not filter.", alias="filterExposed")
    filter_published: Optional[StrictBool] = Field(default=None, description="Whether to filter published content. If null, it will not filter.", alias="filterPublished")
    filter_recycled: Optional[StrictBool] = Field(default=None, description="Whether to filter recycled content. If null, it will not filter.", alias="filterRecycled")
    highlight_post_tag: Optional[StrictStr] = Field(default=None, description="Post HTML tag of highlighted fragment.", alias="highlightPostTag")
    highlight_pre_tag: Optional[StrictStr] = Field(default=None, description="Pre HTML tag of highlighted fragment.", alias="highlightPreTag")
    include_category_names: Optional[List[StrictStr]] = Field(default=None, description="Category names to include(and). If null, it will include all categories.", alias="includeCategoryNames")
    include_owner_names: Optional[List[StrictStr]] = Field(default=None, description="Owner names to include(or). If null, it will include all owners.", alias="includeOwnerNames")
    include_tag_names: Optional[List[StrictStr]] = Field(default=None, description="Tag names to include(and). If null, it will include all tags.", alias="includeTagNames")
    include_types: Optional[List[StrictStr]] = Field(default=None, description="Types to include(or). If null, it will include all types.", alias="includeTypes")
    keyword: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Search keyword.")
    limit: Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]] = Field(default=None, description="Limit of result.")
    __properties: ClassVar[List[str]] = ["annotations", "filterExposed", "filterPublished", "filterRecycled", "highlightPostTag", "highlightPreTag", "includeCategoryNames", "includeOwnerNames", "includeTagNames", "includeTypes", "keyword", "limit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annotations": obj.get("annotations"),
            "filterExposed": obj.get("filterExposed"),
            "filterPublished": obj.get("filterPublished"),
            "filterRecycled": obj.get("filterRecycled"),
            "highlightPostTag": obj.get("highlightPostTag"),
            "highlightPreTag": obj.get("highlightPreTag"),
            "includeCategoryNames": obj.get("includeCategoryNames"),
            "includeOwnerNames": obj.get("includeOwnerNames"),
            "includeTagNames": obj.get("includeTagNames"),
            "includeTypes": obj.get("includeTypes"),
            "keyword": obj.get("keyword"),
            "limit": obj.get("limit")
        })
        return _obj


