# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from halo_client.models.author import Author
from halo_client.models.custom_templates import CustomTemplates
from halo_client.models.license import License
from typing import Optional, Set
from typing_extensions import Self

class ThemeSpec(BaseModel):
    """
    ThemeSpec
    """ # noqa: E501
    author: Author
    config_map_name: Optional[StrictStr] = Field(default=None, alias="configMapName")
    custom_templates: Optional[CustomTemplates] = Field(default=None, alias="customTemplates")
    description: Optional[StrictStr] = None
    display_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="displayName")
    homepage: Optional[StrictStr] = None
    issues: Optional[StrictStr] = None
    license: Optional[List[License]] = None
    logo: Optional[StrictStr] = None
    repo: Optional[StrictStr] = None
    requires: Optional[StrictStr] = None
    setting_name: Optional[StrictStr] = Field(default=None, alias="settingName")
    version: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["author", "configMapName", "customTemplates", "description", "displayName", "homepage", "issues", "license", "logo", "repo", "requires", "settingName", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThemeSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # override the default output from pydantic by calling `to_dict()` of custom_templates
        if self.custom_templates:
            _dict['customTemplates'] = self.custom_templates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in license (list)
        _items = []
        if self.license:
            for _item_license in self.license:
                if _item_license:
                    _items.append(_item_license.to_dict())
            _dict['license'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThemeSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "author": Author.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "configMapName": obj.get("configMapName"),
            "customTemplates": CustomTemplates.from_dict(obj["customTemplates"]) if obj.get("customTemplates") is not None else None,
            "description": obj.get("description"),
            "displayName": obj.get("displayName"),
            "homepage": obj.get("homepage"),
            "issues": obj.get("issues"),
            "license": [License.from_dict(_item) for _item in obj["license"]] if obj.get("license") is not None else None,
            "logo": obj.get("logo"),
            "repo": obj.get("repo"),
            "requires": obj.get("requires"),
            "settingName": obj.get("settingName"),
            "version": obj.get("version")
        })
        return _obj


