# coding: utf-8

"""
    Halo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.22.7
    Contact: hi@halo.run
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UserSpec(BaseModel):
    """
    UserSpec
    """ # noqa: E501
    avatar: Optional[StrictStr] = None
    bio: Optional[StrictStr] = None
    disabled: Optional[StrictBool] = None
    display_name: StrictStr = Field(alias="displayName")
    email: StrictStr
    email_verified: Optional[StrictBool] = Field(default=None, alias="emailVerified")
    login_history_limit: Optional[StrictInt] = Field(default=None, alias="loginHistoryLimit")
    password: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    registered_at: Optional[datetime] = Field(default=None, alias="registeredAt")
    totp_encrypted_secret: Optional[StrictStr] = Field(default=None, alias="totpEncryptedSecret")
    two_factor_auth_enabled: Optional[StrictBool] = Field(default=None, alias="twoFactorAuthEnabled")
    __properties: ClassVar[List[str]] = ["avatar", "bio", "disabled", "displayName", "email", "emailVerified", "loginHistoryLimit", "password", "phone", "registeredAt", "totpEncryptedSecret", "twoFactorAuthEnabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "avatar": obj.get("avatar"),
            "bio": obj.get("bio"),
            "disabled": obj.get("disabled"),
            "displayName": obj.get("displayName"),
            "email": obj.get("email"),
            "emailVerified": obj.get("emailVerified"),
            "loginHistoryLimit": obj.get("loginHistoryLimit"),
            "password": obj.get("password"),
            "phone": obj.get("phone"),
            "registeredAt": obj.get("registeredAt"),
            "totpEncryptedSecret": obj.get("totpEncryptedSecret"),
            "twoFactorAuthEnabled": obj.get("twoFactorAuthEnabled")
        })
        return _obj


